name: analisedobrasil
services:
  db:
    environment:
      POSTGRES_DB: macro
      POSTGRES_PASSWORD: etl123
      POSTGRES_USER: etl
    image: postgres:16
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5432
        published: "5433"
        protocol: tcp
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
        volume: {}
  etl:
    build:
      context: C:\Users\Yuri\Desktop\Analise do Brasil
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
        required: true
    environment:
      DATABASE_URL: postgresql+psycopg2://etl:etl123@db:5432/macro
    networks:
      default: null
    volumes:
      - type: bind
        source: C:\Users\Yuri\Desktop\Analise do Brasil\src
        target: /app/src
        bind: {}
      - type: bind
        source: C:\Users\Yuri\Desktop\Analise do Brasil\requirements.txt
        target: /app/requirements.txt
        bind: {}
networks:
  default:
    name: analisedobrasil_default
volumes:
  pgdata:
    name: analisedobrasil_pgdata